# ----------------------------
# Makefile Options
# ----------------------------

NAME = AAA
ICON = icon.png
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

include $(shell cedev-config --makefile)